# Created using wingetcreate

PackageIdentifier: IObit.IObitUnlocker
PackageVersion: 1.2.0.1
PackageLocale: en-US
Publisher: IObit
PackageName: IObit Unlocker
License: https://www.iobit.com/en/legal.php
ShortDescription: IObit Unlocker
ManifestType: defaultLocale
ManifestVersion: 1.0.0
